package com.apptimistiq.android.fitstreak.main.data.database

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Database entity representing a user's daily health and fitness activities.
 *
 * This class serves as the primary data model for storing fitness tracking information
 * in the Room database. Each instance represents a single day's recorded activities
 * including hydration, sleep, exercise, and movement metrics.
 *
 * @property id Unique identifier for the activity record
 * @property dateOfActivity Timestamp when the activity was recorded (stored as epoch milliseconds)
 * @property waterGlasses Number of water glasses consumed
 * @property sleepHours Hours of sleep recorded
 * @property exerciseCalories Calories burned during exercise activities
 * @property steps Total step count for the day
 */
@Entity(tableName = "activity_store")
data class Activity(
    /**
     * Unique identifier for the activity record.
     * Auto-generated by Room when a new activity is inserted into the database.
     */
    @PrimaryKey(autoGenerate = true) 
    val id: Long = 0L,
    
    /**
     * Timestamp of when this activity was recorded.
     * Stored as epoch time in milliseconds.
     */
    @ColumnInfo(name = "date_of_activity") 
    val dateOfActivity: Long,
    
    /**
     * Number of water glasses consumed.
     * Used to track daily hydration levels.
     */
    @ColumnInfo(name = "water_glasses") 
    val waterGlasses: Int,
    
    /**
     * Hours of sleep recorded.
     * Used to track sleep duration.
     */
    @ColumnInfo(name = "sleep_hrs") 
    val sleepHours: Int,
    
    /**
     * Calories burned during exercise activities.
     * Tracks energy expenditure from workouts.
     */
    @ColumnInfo(name = "exercise_cal") 
    val exerciseCalories: Int,
    
    /**
     * Total step count for the day.
     * Measures daily movement and activity level.
     */
    @ColumnInfo(name = "steps") 
    val steps: Int
)
